# 随机抽样

In [1]:
import numpy as np

In [3]:
np.__version__

'1.11.2'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## 简单随机数据

Q1、创建一个形状为(3, 2)的数组，并使用在[0, 1)上均匀分布的随机样本对其进行填充。 

In [2]:
np.random.rand(3,2)

array([[0.41635749, 0.91209604],
       [0.38182629, 0.16031033],
       [0.11518388, 0.73852356]])

Q2、创建一个形状为(1000, 1000)的数组，并使用来自标准正态分布的随机样本对其进行填充。然后验证其均值和标准差分别足够接近0和1。 

1.000325986568629

Q3、创建一个形状为(3, 2)的数组，并使用来自离散均匀分布的、取值范围在0到3（包含0和3）之间的随机整数对其进行填充。 

array([[1, 0],
       [2, 3],
       [1, 0]])

Q4、从数组 x 中随机抽取1个元素，使得抽取每个元素的概率分别为 0.3 、0.5 、 0.2 。然后将抽取结果打印10次。 

In [ ]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']

b'2 out of 10'

Q5、从0到9中以相同的概率随机抽取3个不同的整数。 

array([[6, 1, 7]])

## 排列

Q6、对0到9（包含0和9）之间的数字进行打乱顺序操作。 

array([2, 6, 0, 4, 8, 3, 7, 5, 1, 9])

In [3]:
# Or


## 随机数生成器

Q7、将随机数生成器的种子设置为10，这样你下次就能得到相同的值。 