# 随机抽样

In [2]:
import numpy as np

In [3]:
np.__version__

'1.11.2'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## 简单随机数据

Q1、创建一个形状为(3, 2)的数组，并使用在[0, 1)上均匀分布的随机样本对其进行填充。 

In [49]:
np.random.rand(3, 2) 
# Or np.random.random((3,2))

array([[ 0.13879034,  0.71300174],
       [ 0.08121322,  0.00393554],
       [ 0.02349471,  0.56677474]])

Q2、创建一个形状为(1000, 1000)的数组，并使用来自标准正态分布的随机样本对其进行填充。然后验证其均值和标准差分别足够接近0和1。 

In [42]:
out1 = np.random.randn(1000, 1000)
out2 = np.random.standard_normal((1000, 1000))
out3 = np.random.normal(loc=0.0, scale=1.0, size=(1000, 1000))
assert np.allclose(np.mean(out1), np.mean(out2), atol=0.1)
assert np.allclose(np.mean(out1), np.mean(out3), atol=0.1)
assert np.allclose(np.std(out1), np.std(out2), atol=0.1)
assert np.allclose(np.std(out1), np.std(out3), atol=0.1)
print np.mean(out3)
print np.std(out1)


-0.00110028519551
0.999683483393


Q3、创建一个形状为(3, 2)的数组，并使用来自离散均匀分布的、取值范围在0到3（包含0和3）之间的随机整数对其进行填充。 

In [44]:
np.random.randint(0, 4, (3, 2))

array([[1, 3],
       [3, 0],
       [0, 0]])

Q4、从数组 x 中随机抽取1个元素，使得抽取每个元素的概率分别为 0.3 、0.5 、 0.2 。然后将抽取结果打印10次。 

In [58]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']

In [60]:
for _ in range(10):
    print np.random.choice(x, p=[.3, .5, .2])

2 out of 10
5 out of 10
3 out of 10
5 out of 10
5 out of 10
5 out of 10
2 out of 10
2 out of 10
5 out of 10
5 out of 10


Q5、从0到9中以相同的概率随机抽取3个不同的整数。 

In [66]:
np.random.choice(10, 3, replace=False)

array([5, 4, 0])

## 排列

Q6、对0到9（包含0和9）之间的数字进行打乱顺序操作。 

In [86]:
x = np.arange(10)
np.random.shuffle(x)
print x

[2 3 8 4 5 1 0 6 9 7]


In [88]:
# Or
print np.random.permutation(10)

[5 2 7 4 1 0 6 8 9 3]


## 随机数生成器

Q7、将随机数生成器的种子设置为10，这样你下次就能得到相同的值。 

In [91]:
np.random.seed(10)