# 集合操作例程

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [6]:
author = 'kyubyong. longinglove@nate.com'

## 构建合适的集合

Q1、从  x 中获取唯一元素和重构索引。然后重构 x 。 

In [ ]:
x = np.array([1, 2, 6, 4, 2, 3, 2])


(array([1, 2, 3, 4, 6]), array([0, 1, 4, 3, 1, 2, 1]))

## 布尔运算

Q2、创建一个与 x 形状相同的布尔数组。如果 x 的每个元素都存在于 y 中，结果为“真”（True），否则为“假”（False）。 

In [ ]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1])


array([ True,  True, False, False,  True])

Q3、找出 x 和 y 的唯一交集。 

In [ ]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])

array([0, 1])

Q4、找出 x 中不存在于 y 中的唯一元素。 

In [ ]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


array([2, 5])

Q5、找出 x 和 y 的异或元素。 

In [ ]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


array([2, 4, 5])

Q6、找出 x 和 y 的并集。 

In [ ]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


array([0, 1, 2, 4, 5])