# 排序、搜索与计数

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## 排序

Q1、沿着第二轴对x进行排序。 

In [ ]:
x = np.array([[1,4],[3,1]])


array([[1, 4],
       [1, 3]])

Q2、对姓氏和名字的组合对进行排序，并返回它们的索引。（先按姓氏排序，然后按名字排序）。 

In [ ]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')


array([1, 2, 0])

Q3、获取能使`x`沿着第二轴进行排序的索引。 

In [6]:
x = np.array([[1,4],[3,1]])
np.argsort(x,axis=1)

array([[0, 1],
       [1, 0]])

Q4、创建一个数组，使得它的第五个元素与已排序的x的对应元素相同，并且该数组中其他元素是用它们各自的值去除以自身（结果为 1） 。

In [ ]:
x = np.random.permutation(10)
# print "x =", x


array([0, 1, 2, 3, 4, 5, 6, 8, 9, 7])

Q5、创建一个数组的索引，使得该数组的第三个元素与已排序的`x`的对应元素相同，并且该数组中其他元素是用它们各自的值去除以自身。 

In [ ]:
x = np.random.permutation(10)
# print "x =", x


array([0, 1, 2, 3, 8, 6, 7, 9, 4, 5])

## 搜索

Q6、沿着第二轴获取`x`的最大值和最小值以及它们对应的索引。 

In [ ]:
x = np.random.permutation(10).reshape(2, 5)
# print "x =", x


array([4, 1])

Q7、沿着第二轴获取`x`的最大值和最小值以及它们对应的索引，忽略其中的NaN（非数字）值。 

In [ ]:
x = np.array([[np.nan, 4], [3, 2]])


array([1, 0])

Q8、获取数组`x`中大于2的元素的值及其索引。 

In [ ]:
x = np.array([[1, 2, 3], [1, 3, 5]])



(array([0, 1, 1]), array([2, 1, 2]))

Q9、获取展平后的数组`x`中大于2的元素的索引。 

In [ ]:
x = np.array([[1, 2, 3], [1, 3, 5]])


(array([2, 4, 5]),)

Q10、检查数组`x`的元素，如果元素小于0则返回0，否则返回元素本身。 

In [ ]:
x = np.arange(-5, 4).reshape(3, 3)


array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11、获取将数组`y`的元素插入到数组`x`中以保持有序的插入位置索引。

In [26]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x,y)

array([0, 2, 1, 3])

## 计数

Q12、获取数组`x`中非零元素的数量。

In [ ]:
x = [[0,1,7,0,0],[3,0,0,2,19]]


5