# 排序、搜索与计数

In [3]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## 排序

Q1、沿着第二轴对x进行排序。 

In [11]:
x = np.array([[1,4],[3,1]])
out = np.sort(x, axis=1)
x.sort(axis=1)
assert np.array_equal(out, x)
print out

[[1 4]
 [1 3]]


Q2、对姓氏和名字的组合对进行排序，并返回它们的索引。（先按姓氏排序，然后按名字排序）。 

In [13]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
print np.lexsort((first_names, surnames))

[1 2 0]


Q3、获取能使`x`沿着第二轴进行排序的索引。 

In [17]:
x = np.array([[1,4],[3,1]])
out = np.argsort(x, axis=1)
print out

[[0 1]
 [1 0]]


Q4、创建一个数组，使得它的第五个元素与已排序的x的对应元素相同，并且该数组中其他元素是用它们各自的值去除以自身（结果为 1） 。

In [48]:
x = np.random.permutation(10)
print "x =", x
print "\nCheck the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5\n", 
out = np.partition(x, 5)
x.partition(5) # in-place equivalent
assert np.array_equal(x, out)
print out


x = [5 1 6 3 9 8 2 7 4 0]

Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5
[2 0 4 3 1 5 8 7 6 9]


Q5、创建一个数组的索引，使得该数组的第三个元素与已排序的`x`的对应元素相同，并且该数组中其他元素是用它们各自的值去除以自身。 

In [56]:
x = np.random.permutation(10)
print "x =", x
partitioned = np.partition(x, 3)
indices = np.argpartition(x, 3)
print "partitioned =", partitioned
print "indices =", partitioned
assert np.array_equiv(x[indices], partitioned)

x = [2 8 3 7 5 6 4 0 9 1]
partitioned = [0 1 2 3 4 5 8 6 9 7]
indices = [0 1 2 3 4 5 8 6 9 7]


## 搜索

Q6、沿着第二轴获取`x`的最大值和最小值以及它们对应的索引。 

In [78]:
x = np.random.permutation(10).reshape(2, 5)
print "x =", x
print "maximum values =", np.max(x, 1)
print "max indices =", np.argmax(x, 1)
print "minimum values =", np.min(x, 1)
print "min indices =", np.argmin(x, 1)


x = [[0 5 9 8 2]
 [3 7 4 1 6]]
maximum values = [9 7]
max indices = [2 1]
minimum values = [0 1]
min indices = [0 3]


Q7、沿着第二轴获取`x`的最大值和最小值以及它们对应的索引，忽略其中的NaN（非数字）值。 

In [79]:
x = np.array([[np.nan, 4], [3, 2]])
print "maximum values ignoring NaNs =", np.nanmax(x, 1)
print "max indices =", np.nanargmax(x, 1)
print "minimum values ignoring NaNs =", np.nanmin(x, 1)
print "min indices =", np.nanargmin(x, 1)

maximum values ignoring NaNs = [ 4.  3.]
max indices = [1 0]
minimum values ignoring NaNs = [ 4.  2.]
min indices = [1 1]


Q8、获取数组`x`中大于2的元素的值及其索引。 

In [113]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print "Values bigger than 2 =", x[x>2]
print "Their indices are ", np.nonzero(x > 2)
assert np.array_equiv(x[x>2], x[np.nonzero(x > 2)])
assert np.array_equiv(x[x>2], np.extract(x > 2, x))

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9、获取展平后的数组`x`中大于2的元素的索引。 

In [4]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print np.flatnonzero(x>2)
assert np.array_equiv(np.flatnonzero(x), x.ravel().nonzero())

[2 4 5]


Q10、检查数组`x`的元素，如果元素小于0则返回0，否则返回元素本身。 

In [105]:
x = np.arange(-5, 4).reshape(3, 3)
print np.where(x <0, 0, x)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11、获取将数组`y`的元素插入到数组`x`中以保持有序的插入位置索引。

In [109]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)

array([0, 2, 1, 3], dtype=int64)

## 计数

Q12、获取数组`x`中非零元素的数量。

In [120]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
print np.count_nonzero(x)
assert np.count_nonzero(x) == len(x[x!=0])

5
