# 数组创建过程

## 全1数组与全0数组

In [1]:
import numpy as np

创建一个新的 2*2 整数数组，不初始化数组元素。

array([[0., 0.],
       [0., 0.]])

设 X = np.array([1,2,3], [4,5,6], np.int32) ，
创建一个与 X 具有相同形状和类型的新数组。

In [ ]:
X = np.array([[1,2,3], [4,5,6]], np.int32)


array([[         0, 1074266112,          0],
       [1073741824,          0, 1072693248]], dtype=int32)

创建一个三维数组，使其对角线上的元素为 1，其他位置的元素为 0。 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

创建一个新的 3*2 的浮点数数组，并用 1 填充该数组。 

设 x = np.arange(4, dtype=np.int64)，创建一个与 x 具有相同形状和类型且元素全为 1 的数组。 

In [ ]:
x = np.arange(4, dtype=np.int64)

创建一个新的 3*2 的浮点数数组，并用 0 填充该数组。 

设 x = np.arange(4, dtype=np.int64)，创建一个与 x 具有相同形状和类型且元素全为 0 的数组。 

In [ ]:
x = np.arange(4, dtype=np.int64)


创建一个新的 2*5 的无符号整数数组，并使用 6 填充该数组。 

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

设 x = np.arange(4, dtype=np.int64)。创建一个与 x 具有相同形状和类型且元素全为 6 的数组。 

In [3]:
x = np.arange(4, dtype=np.int64)


array([6, 6, 6, 6])

## 根据现有数据创建

创建一个包含[1, 2, 3]的数组。

设 x = [1, 2] ，将其转换为一个array。

In [6]:
x = [1,2]
np.asarray(x)

array([1, 2])

设 X = np.array([[1, 2], [3, 4]]) ，将其转换为一个matrix。 

In [ ]:
X = np.array([[1, 2], [3, 4]])


matrix([[1, 2],
        [3, 4]])

设 x=[1,2] ，将其转换为一个 `float` 类型的数组。

In [13]:
x = [1, 2]



In [ ]:
# ❌另一种方法


array([1., 2.])

设 x = np.array([30]) ，将其转换为其单个元素对应的标量，即 30 。

In [16]:
x = np.array([30])


30

设 x = np.array([1, 2, 3]) ，创建 x 的一个数组副本，该副本的id与 x 不同。 

In [ ]:
x = np.array([1, 2, 3])



## 根据数值范围创建

创建一个包含 2、4、6、8、...、100 的数组。 

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

创建一个一维数组，该数组包含 50 个在 3.（包含）到 10.（包含）之间均匀分布的元素。 

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

创建一个包含 50 个元素的一维数组，这些元素在对数尺度上均匀分布于 3.（不包含）到 10.（不包含）之间。

array([1.00000000e+03, 1.38038426e+03, 1.90546072e+03, 2.63026799e+03,
       3.63078055e+03, 5.01187234e+03, 6.91830971e+03, 9.54992586e+03,
       1.31825674e+04, 1.81970086e+04, 2.51188643e+04, 3.46736850e+04,
       4.78630092e+04, 6.60693448e+04, 9.12010839e+04, 1.25892541e+05,
       1.73780083e+05, 2.39883292e+05, 3.31131121e+05, 4.57088190e+05,
       6.30957344e+05, 8.70963590e+05, 1.20226443e+06, 1.65958691e+06,
       2.29086765e+06, 3.16227766e+06, 4.36515832e+06, 6.02559586e+06,
       8.31763771e+06, 1.14815362e+07, 1.58489319e+07, 2.18776162e+07,
       3.01995172e+07, 4.16869383e+07, 5.75439937e+07, 7.94328235e+07,
       1.09647820e+08, 1.51356125e+08, 2.08929613e+08, 2.88403150e+08,
       3.98107171e+08, 5.49540874e+08, 7.58577575e+08, 1.04712855e+09,
       1.44543977e+09, 1.99526231e+09, 2.75422870e+09, 3.80189396e+09,
       5.24807460e+09, 7.24435960e+09])

## 构建矩阵

设 X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]])，
获取 X 的对角线元素，即 [0, 5, 10] 。 

In [10]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])


array([ 0,  5, 10])

创建一个二维数组，其对角线上的元素等于 [1, 2, 3, 4] ，而其他位置的元素为0。 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

创建一个如下所示的数组。
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

创建一个如下所示的数组。
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

创建一个如下所示的数组。 array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])