# 数组操作过程

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

Q1、设 x 是一个形状为 [10, 10, 3] 且所有元素都设置为 1 的NumPy数组，对 x 进行重塑 reshape 操作，使得第二维的大小等于 150 。 

In [5]:
x = np.ones([10, 10, 3])
out = np.reshape(x, [-1, 150])
print out
assert np.allclose(out, np.ones([10, 10, 3]).reshape([-1, 150]))

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  

Q2、设 x 是数组 [[1, 2, 3], [4, 5, 6]] ，将它转换为[1 4 2 5 3 6] 。 

In [22]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out1 = np.ravel(x, order='F')
out2 = x.flatten(order="F")
assert np.allclose(out1, out2)
print out1


[1 4 2 5 3 6]


Q3、设 x 为数组 [[1, 2, 3], [4, 5, 6]] ，获取第5个元素。 

In [23]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out1 = x.flat[4]
out2 = np.ravel(x)[4]
assert np.allclose(out1, out2)
print out1


5


Q4、设 x 是一个形状为 (3, 4, 5) 的任意三维数组。对 x 的维度进行置换，使得新的形状变为 (4, 3, 5) 。 

In [36]:
x = np.zeros((3, 4, 5))
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose([1, 0, 2])
assert out1.shape == out2.shape
print out1.shape

(4L, 3L, 5L)


Q5、设 x 是一个形状为 (3, 4) 的任意二维数组。对 x 的维度进行置换，使得新的形状变为 (4, 3) 。 

In [38]:
x = np.zeros((3, 4))
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose()
out3 = x.T
assert out1.shape == out2.shape == out3.shape
print out1.shape

(4L, 3L)


Q5、设 x 是一个形状为 (3, 4) 的任意二维数组。插入一个新的轴，使得新的形状变为 (3, 1, 4) 。 

In [42]:
x = np.zeros((3, 4))
print np.expand_dims(x, axis=1).shape

(3L, 1L, 4L)


Q6、设 x 是一个形状为 (3, 4, 1) 的任意三维数组。移除单维度的元素，使得新的形状变为 (3, 4) 。 

In [43]:
x = np.zeros((3, 4, 1))
print np.squeeze(x).shape

(3L, 4L)


Q7、设 x 为一个数组<br/>
[[ 1  2  3]<br/>
 [ 4  5  6]]<br/>
且 y 为一个数组<br/>
[[ 7  8  9]<br/>
 [10 11 12]]。<br/>

将 x 和 y 连接起来，使得新数组看起来像<br/>
[[1, 2, 3, 7, 8, 9], <br/>
 [4, 5, 6, 10, 11, 12]]。 <br/>

In [31]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
out1 = np.concatenate((x, y), 1)
out2 = np.hstack((x, y))
assert np.allclose(out1, out2)
print out2

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q8、设 x 为一个数组<br/>
[[ 1  2  3]<br/>
 [ 4  5  6]]<br/>

且 y 为一个数组<br/>
[[ 7  8  9]<br/>
 [10 11 12]]。<br/>

将 x 和 y 连接起来，使得新数组看起来像<br/>
[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]] <br/>


In [38]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
out1 = np.concatenate((x, y), 0)
out2 = np.vstack((x, y))
assert np.allclose(out1, out2)
print out2

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q8、设 x 是一个数组 [1 2 3] ， y 是 [4 5 6] 。将其转换为 [[1, 4], [2, 5], [3, 6]] 。 

In [9]:
x = np.array((1,2,3))
y = np.array((4,5,6))
out1 = np.column_stack((x, y))
out2 = np.squeeze(np.dstack((x, y)))
out3 = np.vstack((x, y)).T
assert np.allclose(out1, out2)
assert np.allclose(out2, out3)
print out1


array([[1, 4],
       [2, 5],
       [3, 6]])

Q9、设 x 为一个数组 [[1],[2],[3]] ， y 为 [[4], [5], [6]] 。将 x 转换为 [[[1, 4]], [[2, 5]], [[3, 6]]] 。 

In [34]:
x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])
out = np.dstack((x, y))
print out


[[[1 4]]

 [[2 5]]

 [[3 6]]]


Q10、设 x 是一个数组 [1, 2, 3, …, 9] 。将 x 拆分成三个数组，按照原始顺序，这三个数组分别有 4 个、 2 个和 3 个元素。 

In [62]:
x = np.arange(1, 10)
print np.split(x, [4, 6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q11、设 x 为一个数组 <br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>

 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]]。<br/>
将其拆分为两个数组，使得第一个数组看起来像<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>

 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]]。<br/>

并且第二个数组看起来像：<br/>
[[[  3.],<br/>
  [  7.]],<br/>

 [[  11.],<br/>
  [ 15.]]]。<br/>

In [72]:
x = np.arange(16).reshape(2, 2, 4)
out1 = np.split(x, [3],axis=2)
out2 = np.dsplit(x, [3])
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])
print out1


[array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]


Q12、设 x 为一个数组<br/>
[[  0.,   1.,   2.,   3.],<br/>
 [  4.,   5.,   6.,   7.],<br/>
 [  8.,   9.,  10.,  11.],<br/>
 [ 12.,  13.,  14.,  15.]]。<br/>
沿着第二个轴将其拆分成两个数组。 

In [74]:
x = np.arange(16).reshape((4, 4))
out1 = np.hsplit(x, 2)
out2 = np.split(x, 2, 1)
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])
print out1

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


Q13、设 x 为一个数组<br/>
[[  0.,   1.,   2.,   3.],<br/>
 [  4.,   5.,   6.,   7.],<br/>
 [  8.,   9.,  10.,  11.],<br/>
 [ 12.,  13.,  14.,  15.]]。<br/>
沿着第一个轴将其拆分成两个数组。 

In [75]:
x = np.arange(16).reshape((4, 4))
out1 = np.vsplit(x, 2)
out2 = np.split(x, 2, 0)
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])
print out1

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


Q14、设 x 是一个数组 [0, 1, 2] 。将其转换为<br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]]。 <br/>

In [93]:
x = np.array([0, 1, 2])
out1 = np.tile(x, [2, 2])
out2 = np.resize(x, [2, 6])
assert np.allclose(out1, out2)
print out1

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


Q15、设 x 为一个数组 [0, 1, 2]。将其转换为<br/>
[0, 0, 1, 1, 2, 2] 。 

In [83]:
x = np.array([0, 1, 2])
print np.repeat(x, 2)

[0 0 1 1 2 2]


Q16、设 x 是一个数组 [0, 0, 0, 1, 2, 3, 0, 2, 1, 0] 。<br/>
去掉开头和结尾的零。 

In [105]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
out = np.trim_zeros(x)
print out

[1 2 3 0 2 1]


Q17、设 x 是一个数组 [2, 2, 1, 5, 4, 5, 1, 2, 3]。获取包含唯一元素及其出现次数的两个数组。 

In [107]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
u, indices = np.unique(x, return_counts=True)
print u, indices

[1 2 3 4 5] [2 3 1 1 2]


Q18、设 x 为一个数组<br/>
[[1  2]
 [3  4]]<br/>
沿第二个轴翻转 x 。

In [120]:
x = np.array([[1,2], [3,4]])
out1 = np.fliplr(x)
out2 = x[:, ::-1]
assert np.allclose(out1, out2)
print out1

[[2 1]
 [4 3]]


Q19、设 x 为一个数组<br/>
[[1  2]
 [3  4]]<br/>
沿第一个轴翻转 x 。

In [121]:
x = np.array([[1,2], [3,4]])
out1 = np.flipud(x)
out2 = x[::-1, :]
assert np.allclose(out1, out2)
print out1

[[3 4]
 [1 2]]


Q20、设 x 为一个数组<br/>
[[1  2]
 [3  4]]<br/>
将 x 逆时针旋转90度。

In [122]:
x = np.array([[1,2], [3,4]])
out = np.rot90(x)
print out

[[2 4]
 [1 3]]


Q21、设 x 是一个数组<br/>
[[1 2 3 4]
 [5 6 7 8]]<br/>
沿第二个轴将元素向右移动一步。

In [126]:
x = np.arange(1, 9).reshape([2, 4])
print np.roll(x, 1, axis=1)

[[4 1 2 3]
 [8 5 6 7]]
