# 数组操作过程

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

Q1、设 x 是一个形状为 [10, 10, 3] 且所有元素都设置为 1 的NumPy数组，对 x 进行重塑 reshape 操作，使得第二维的大小等于 150 。 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

Q2、设 x 是数组 [[1, 2, 3], [4, 5, 6]] ，将它转换为[1 4 2 5 3 6] 。 

array([[1, 4, 2, 5, 3, 6]])

Q3、设 x 为数组 [[1, 2, 3], [4, 5, 6]] ，获取第5个元素。 

5

Q4、设 x 是一个形状为 (3, 4, 5) 的任意三维数组。对 x 的维度进行置换，使得新的形状变为 (4, 3, 5) 。 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

Q5、设 x 是一个形状为 (3, 4) 的任意二维数组。对 x 的维度进行置换，使得新的形状变为 (4, 3) 。 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q5、设 x 是一个形状为 (3, 4) 的任意二维数组。插入一个新的轴，使得新的形状变为 (3, 1, 4) 。 

(3, 1, 4)

Q6、设 x 是一个形状为 (3, 4, 1) 的任意三维数组。移除单维度的元素，使得新的形状变为 (3, 4) 。 

(3, 4)

Q7、设 x 为一个数组<br/>
[[ 1  2  3]<br/>
 [ 4  5  6]]<br/>
且 y 为一个数组<br/>
[[ 7  8  9]<br/>
 [10 11 12]]。<br/>

将 x 和 y 连接起来，使得新数组看起来像<br/>
[[1, 2, 3, 7, 8, 9], <br/>
 [4, 5, 6, 10, 11, 12]]。 <br/>

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q8、设 x 为一个数组<br/>
[[ 1  2  3]<br/>
 [ 4  5  6]]<br/>

且 y 为一个数组<br/>
[[ 7  8  9]<br/>
 [10 11 12]]。<br/>

将 x 和 y 连接起来，使得新数组看起来像<br/>
[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]] <br/>


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q8、设 x 是一个数组 [1 2 3] ， y 是 [4 5 6] 。将其转换为 [[1, 4], [2, 5], [3, 6]] 。 

array([1, 2, 3, 4, 5, 6])

Q9、设 x 为一个数组 [[1],[2],[3]] ， y 为 [[4], [5], [6]] 。将 x 转换为 [[[1, 4]], [[2, 5]], [[3, 6]]] 。 

array([[[1, 4],
        [2, 5],
        [3, 6]]])

Q10、设 x 是一个数组 [1, 2, 3, …, 9] 。将 x 拆分成三个数组，按照原始顺序，这三个数组分别有 4 个、 2 个和 3 个元素。 

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q11、设 x 为一个数组 <br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>

 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]]。<br/>
将其拆分为两个数组，使得第一个数组看起来像<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>

 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]]。<br/>

并且第二个数组看起来像：<br/>
[[[  3.],<br/>
  [  7.]],<br/>

 [[  11.],<br/>
  [ 15.]]]。<br/>

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]),
 array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]])]

Q12、设 x 为一个数组<br/>
[[  0.,   1.,   2.,   3.],<br/>
 [  4.,   5.,   6.,   7.],<br/>
 [  8.,   9.,  10.,  11.],<br/>
 [ 12.,  13.,  14.,  15.]]。<br/>
沿着第二个轴将其拆分成两个数组。 

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

Q13、设 x 为一个数组<br/>
[[  0.,   1.,   2.,   3.],<br/>
 [  4.,   5.,   6.,   7.],<br/>
 [  8.,   9.,  10.,  11.],<br/>
 [ 12.,  13.,  14.,  15.]]。<br/>
沿着第一个轴将其拆分成两个数组。 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Q14、设 x 是一个数组 [0, 1, 2] 。将其转换为<br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]]。 <br/>

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

Q15、设 x 为一个数组 [0, 1, 2]。将其转换为<br/>
[0, 0, 1, 1, 2, 2] 。 

array([0, 0, 1, 1, 2, 2])

Q16、设 x 是一个数组 [0, 0, 0, 1, 2, 3, 0, 2, 1, 0] 。<br/>
去掉开头和结尾的零。 

array([1, 2, 3, 0, 2, 1])

Q17、设 x 是一个数组 [2, 2, 1, 5, 4, 5, 1, 2, 3]。获取包含唯一元素及其出现次数的两个数组。 

(array([1, 2, 3, 4, 5]), array([2, 3, 1, 1, 2]))

Q18、设 x 为一个数组<br/>
[[1  2]
 [3  4]]<br/>
沿第二个轴翻转 x 。

array([[2, 1],
       [4, 3]])

Q19、设 x 为一个数组<br/>
[[1  2]
 [3  4]]<br/>
沿第一个轴翻转 x 。

array([[3, 4],
       [1, 2]])

Q20、设 x 为一个数组<br/>
[[1  2]
 [3  4]]<br/>
将 x 逆时针旋转90度。

array([[2, 4],
       [1, 3]])

Q21、设 x 是一个数组<br/>
[[1 2 3 4]
 [5 6 7 8]]<br/>
沿第二个轴将元素向右移动一步。

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])