## 字符串操作

In [1]:
from __future__ import print_function
import numpy as np

In [2]:
author = "kyubyong. https://github.com/Kyubyong/numpy_exercises"

In [2]:
np.__version__

'1.26.4'

Q1、将x1和x2连接起来。

In [ ]:
x1 = np.array(['Hello', 'Say'], dtype=np.str)
x2 = np.array([' world', ' something'], dtype=np.str)



array(['Hello', 'Say', ' world', ' something'], dtype='<U10')

Q2、逐元素地将x重复三次。

In [ ]:
x = np.array(['Hello ', 'Say '], dtype=np.str)


array(['Hello ', 'Hello ', 'Hello ', 'Say ', 'Say ', 'Say '], dtype='<U6')

Q3-1、逐元素地将x的首字母大写。<br/>
Q3-2、逐元素地将x转换为小写形式。<br/>
Q3-3、逐元素地将x转换为大写形式。<br/>
Q3-4、逐元素地将x中的字母大小写互换。<br/>
Q3-5、逐元素地将x转换为标题格式（每个单词首字母大写，其余字母小写）。<br/> 

In [ ]:
x = np.array(['heLLo woRLd', 'Say sOmething'], dtype=np.str_)
capitalized = ...
lowered = ...
uppered = ...
swapcased = ...
titlecased = ...
print("capitalized =", capitalized)
print("lowered =", lowered)
print("uppered =", uppered)
print("swapcased =", swapcased)
print("titlecased =", titlecased)

capitalized = ['HELLO WORLD' 'SAY SOMETHING']
lowered = Ellipsis
uppered = Ellipsis
swapcased = Ellipsis
titlecased = Ellipsis


Q4、使每个元素的长度为20，并用`_`进行填充，让字符串居中显示/左对齐显示/右对齐显示。 

In [ ]:
x = np.array(['hello world', 'say something'], dtype=np.str_)
centered = ...
left = ...
right = ...

print("centered =", centered)
print("left =", left)
print("right =", right)

centered = ['____hello world_____' '___say something____']
left = ['hello world_________' 'say something_______']
right = ['_________hello world' '_______say something']


Q5、用cp500编码x，然后再对其进行解码。 

In [ ]:
x = np.array(['hello world', 'say something'], dtype=np.str)
encoded = ...
decoded = ...
print("encoded =", encoded)
print("decoded =", decoded)

encoded = [b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'
 b'\xa2\x81\xa8@\xa2\x96\x94\x85\xa3\x88\x89\x95\x87']
decoded = ['hello world' 'say something']


Q6、在x的字符之间插入一个空格。

In [ ]:
x = np.array(['hello world', 'say something'], dtype=np.str)


array(['h e l l o   w o r l d', 's a y   s o m e t h i n g'], dtype='<U25')

Q7-1、逐元素地去除x中字符串开头和结尾的空白字符。<br/>
Q7-2、逐元素地去除x中字符串开头的空白字符。<br/>
Q7-3、逐元素地去除x中字符串结尾的空白字符。 

In [ ]:
x = np.array(['   hello world   ', '\tsay something\n'], dtype=np.str)
stripped = ...
lstripped = ...
rstripped = ...
print("stripped =", stripped)
print("lstripped =", lstripped)
print("rstripped =", rstripped)

stripped = ['hello world' 'say something']
lstripped = ['hello world   ' 'say something\n']
rstripped = ['   hello world' '\tsay something']


Q8、用空格分割x中的元素。

In [ ]:
x = np.array(['Hello my name is John'], dtype=np.str)



array([list(['Hello', 'my', 'name', 'is', 'John'])], dtype=object)

Q9、将x的元素分割成多行。

In [ ]:
x = np.array(['Hello\nmy name is John'], dtype=np.str)


array([list(['Hello', 'my name is John'])], dtype=object)

Q10、将x变成一个4位数字的数字字符串，在其左侧补零。 

In [ ]:
x = np.array(['34'], dtype=np.str_)


array(['0034'], dtype='<U4')

Q11、在x中把“John”替换为“Jim”。 

In [ ]:
x = np.array(['Hello nmy name is John'], dtype=np.str)


array(['Hello nmy name is Jim'], dtype='<U21')

## 比较

Q12、逐元素地返回x1是否等于x2的结果。 

In [ ]:
x1 = np.array(['Hello', 'my', 'name', 'is', 'John'], dtype=np.str)
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'], dtype=np.str)

array([ True,  True,  True,  True, False])

Q13、逐元素地返回x1不等于x2的结果。 

In [ ]:
x1 = np.array(['Hello', 'my', 'name', 'is', 'John'], dtype=np.str)
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'], dtype=np.str)


array([False, False, False, False,  True])

## 字符串信息

Q14、逐元素地统计x中字母“l”的数量。 

In [ ]:
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'], dtype=np.str)


array([2, 0, 0, 0, 1])

Q15、逐元素地统计x中字母“l”首次出现的最低索引位置。 

In [ ]:
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'], dtype=np.str)




array([ 2, -1, -1, -1,  2])

Q16-1、检查x的每个元素是否仅由数字组成。<br/>
Q16-2、检查x的每个元素是否仅由小写字母组成。<br/>
Q16-3、检查x的每个元素是否仅由大写字母组成。 

In [ ]:
x = np.array(['Hello', 'I', 'am', '20', 'years', 'old'], dtype=np.str)
out1 = ...
out2 = ...
out3 = ...
print("Digits only =", out1)
print("Lower cases only =", out2)
print("Upper cases only =", out3)

Digits only = [False False False  True False False]
Lower cases only = [False False  True False  True  True]
Upper cases only = [False  True False False False False]


Q17、检查x的每个元素是否以“hi”开头。

In [ ]:
x = np.array(['he', 'his', 'him', 'his'], dtype=np.str)


array([False,  True,  True,  True])