# 逻辑函数

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## 真值测试

Q1、设 x 是一个任意数组。如果 x 的元素中没有一个是零，就返回 True。提醒一下，在 Python 中，0 的求值结果为 False。 

In [3]:
x = np.array([1,2,3])
#

x = np.array([1,0,3])
#

False

Q2、设 x 是一个任意数组。如果 x 的任意一个元素是非零的，则返回 True。 

In [ ]:
x = np.array([1,0,0])
#

x = np.array([0,0,0])
#


True


## 数组内容

Q3、预测以下代码的运行结果。 

In [ ]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isfinite(x)

array([ True,  True, False, False])

Q4、预测以下代码的运行结果。 

In [10]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isinf(x)

Q5、预测以下代码的运行结果。 

In [12]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isnan(x)

## 数组类型测试

Q6、预测以下代码的运行结果。

In [ ]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print np.iscomplex(x)

array([ True, False, False, False, False,  True])

Q7、预测以下代码的运行结果。

In [ ]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print np.isreal(x)

array([False,  True,  True,  True,  True, False])

Q8、预测以下代码的运行结果。

In [ ]:
#print np.isscalar(3)
#print np.isscalar([3])
#print np.isscalar(True)

True
False
True


## 逻辑运算

Q9、预测以下代码的运行结果。

In [ ]:
#print np.logical_and([True, False], [False, False])
#print np.logical_or([True, False, True], [True, False, False])
#print np.logical_xor([True, False, True], [True, False, False])
#print np.logical_not([True, False, 0, 1])

array([False,  True,  True, False])

## 比较

Q10、预测以下代码的运行结果。

In [ ]:
#print np.allclose([3], [2.999999])
#print np.array_equal([3], [2.999999])

False

Q11、编写 NumPy 比较函数，使其返回的结果如你所见。 

In [ ]:
x = np.array([4, 5])
y = np.array([2, 5])
#
#
#
#

array([False,  True])

Q12、预测以下代码的运行结果。

In [ ]:
#print np.equal([1, 2], [1, 2.000001])
#print np.isclose([1, 2], [1, 2.000001])

array([ True,  True])