# 数学函数

In [1]:
import numpy as np

In [ ]:
np.__version__

In [ ]:
__author__ = "kyubyong. kbpark.linguist@gmail.com. https://github.com/kyubyong"

## 三角函数

Q1、按元素计算 x 的正弦、余弦和正切值。 

In [ ]:
x = np.array([0., 1., 30, 90])


Q2、按元素计算 x 的反正弦、反余弦和反正切值。 

In [ ]:
x = np.array([-1., 0, 1.])

array([-1.57079633,  0.        ,  1.57079633])

Q3、将角度从弧度转换为度数。

In [ ]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])


array([-180.,  -90.,   90.,  180.])

Q4、将角度从度数转换为弧度。

In [ ]:
x = np.array([-180.,  -90.,   90.,  180.])


## 双曲函数

Q5、按元素计算 x 的双曲正弦、双曲余弦和双曲正切值。

In [ ]:
x = np.array([-1., 0, 1.])

## 舍入

Q6、预测这些的结果，要留意这类函数之间的区别。 

In [ ]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x)
out2 = np.floor(x)
out3 = np.ceil(x)
out4 = np.trunc(x)
out5 = [round(elem) for elem in x]

#print out1
#print out2
#print out3
#print out4
#print out5

[2, 2, 2, 3, -2, -2, -3]

Q7、使用 NumPy 实现上述问题中的 out5。 

array([ 2.,  2.,  3.,  3., -2., -3., -3.])

## 求和、求积、求差

Q8、预测这些的结果。

In [ ]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = [np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "",
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "",
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),
        "",
        np.cumprod(x),
        np.cumprod(x, axis=0),
        np.cumprod(x, axis=1),
        "",
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]
           
for out in outs:
    if out == "":
        pass
        #print
    else:
        pass
        #print("->", out)


array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26]])

Q9、按元素计算相邻元素之间的差值。

In [ ]:
x = np.array([1, 2, 4, 7, 0])


array([ 1,  2,  3, -7])

Q10、按元素计算相邻元素之间的差值，并在其前面添加 [0, 0]，在其后面添加 [100]。

In [ ]:
x = np.array([1, 2, 4, 7, 0])


array([  1,   2,   4,   7,   0, 100])

Q11、返回 x 和 y 的叉积。

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])



array([-3,  6, -3])

## 指数与对数

Q12、按元素计算$e^x$的值。 

In [ ]:
x = np.array([1., 2., 3.], np.float32)


array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

Q13、对 x 中的所有元素计算 exp(x) - 1 的值。 

In [ ]:
x = np.array([1., 2., 3.], np.float32)


array([ 1.7182819,  6.389056 , 19.085537 ], dtype=float32)

Q14、对 x 中的所有 p 计算 $2^p$的值。 

In [ ]:
x = np.array([1., 2., 3.], np.float32)


array([2., 4., 8.], dtype=float32)

Q15、按元素计算 x 的自然对数、以 10 为底的对数以及以 2 为底的对数。 

In [ ]:
x = np.array([1, np.e, np.e**2])


array([0.        , 1.44269504, 2.88539008])

Q16、以浮点数精度计算 x 中每个元素加 1 后的自然对数。 

In [ ]:
x = np.array([1e-99, 1e-100])


array([1.e-099, 1.e-100])

## 浮点运算例程 

Q17、按元素返回符号位被设置（为 1）时结果为 True 的情况。 

In [ ]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])



array([ True,  True,  True, False, False, False, False])

Q18、按元素将 x 的符号变为与 y 的符号一致。 

In [ ]:
x = np.array([-1, 0, 1])
y = -1.1



array([-1., -0., -1.])

## 算术运算

Q19、按元素将 x 和 y 相加。 

In [ ]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])


array([0, 0, 0])

Q20、按元素从 x 中减去 y。

In [ ]:
x = np.array([3, 4, 5])
y = np.array(3)


array([0, 1, 2])

Q21、按元素将 x 与 y 相乘。

In [ ]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])


array([ 3,  0, -5])

Q22、用两种不同的方式按元素将 x 除以 y。 

In [ ]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])

array([3., 2., 1.])

Q23、按元素计算 x 的数值负值。 

In [ ]:
x = np.array([1, -1])



array([-1,  1])

Q24、按元素计算 x 的倒数。

In [ ]:
x = np.array([1., 2., .2])



array([1. , 0.5, 5. ])

Q25、按元素计算 $x^y$ 的值。

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])


array([[ 1,  4],
       [ 3, 16]])

Q26、用两种不同的方式按元素计算 x 除以 y 的余数。 

In [4]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2


array([-1,  0, -1,  1,  0,  1])

## 杂项

Q27、如果 x 的某个元素小于 3，则将其替换为 3。
并且如果 x 的某个元素大于 7，则将其替换为 7。 

In [ ]:
x = np.arange(10)



array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

Q28、按元素计算 x 的平方。

In [ ]:
x = np.array([1, 2, -1])

array([1, 4, 1])

Q29、按元素计算 x 的平方根。

In [ ]:
x = np.array([1., 4., 9.])


array([1., 2., 3.])

Q30、计算 x 的绝对值。

In [ ]:
x = np.array([[1, -1], [3, -3]])


array([[1, 1],
       [3, 3]])

Q31. 按元素计算 x 的符号的逐元素指示（即得到表示 x 中每个元素符号的结果）。  

In [ ]:
x = np.array([1, 3, 0, -1, -3])

array([ 1,  1,  0, -1, -1])